update quick-start.md file
gatsbyjs/gatsby-gu pull request #4
Opened 2019-11-19 17:48 UTC by mrmakadia94

File the not fully completed  but till that review changes for the file.

2019-11-20 02:41 UTC, kishanjasani requested changes
@mrmakadia94 Please comment on issue that you start translating with this or that file.

2019-11-20 02:41 UTC, kishanjasani commented on docs/docs/quick-start.md
> +**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી આદેશ `npx gatsby new` ચાલવો એ `gatsby new`
We can keep `Command with કમાન્ડ or આદેશ`. I think કમાન્ડ will be better for understanding.

2019-11-20 02:41 UTC, kishanjasani commented on docs/docs/quick-start.md
> +**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી આદેશ `npx gatsby new` ચાલવો એ `gatsby new`
```suggestion
**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી આદેશ `npx gatsby new` ચલાવો એ `gatsby new` ચલાવા જેવું જ છે.
```

2019-11-26 17:40 UTC, mrmakadia94 commented
Complete the file translation in Gujarati please check and review it.

2019-11-26 21:48 UTC, sagarnasit requested changes
@mrmakadia94 I have added few feedbacks.

2019-11-26 21:48 UTC, sagarnasit commented on docs/docs/quick-start.md
> +શીર્ષક: ઝડપી શરૂઆત
Use `title` instead of `શીર્ષક`.

2019-11-26 21:48 UTC, sagarnasit commented on docs/docs/quick-start.md
> +Gatsby એ ડિફોલટ રૂપે `localhost:8000` ઉપયોગ કરી શકાય તેવા ગરમ-ફરીથી લોડિંગ ડેવલપમેન્ટ એન્વાયર્નમેન્ટ ની શરૂઆત કરશે.
Use `હોટ રિલોડીંગ​` instead of `ગરમ-ફરીથી લોડિંગ`

2019-11-26 21:48 UTC, sagarnasit commented on docs/docs/quick-start.md
> +Gatsby તમારી સાઇટ માટે ઓપ્ટિમાઇઝ પ્રોડક્શન બિલ્ડ બનાવશે, જે રૂટ દીઠ સ્થિર HTML અને જાવાસ્ક્રિપ્ટ કોડ બનાવશે.
Word `સ્ટેટીક​ HTML` makes more sense than `સ્થિર HTML` here.

2019-11-27 17:05 UTC, mrmakadia94 commented
Please review changes @sagarnasit

2019-11-27 19:32 UTC, kishanjasani commented on docs/docs/quick-start.md
> +**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી કમાન્ડ `npx gatsby new` ચાલવો એ `gatsby ne
```suggestion
**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી કમાન્ડ `npx gatsby new` ચલાવો એ `gatsby new` ચલાવવા જેવું જ છે.
```

2019-11-27 19:35 UTC, kishanjasani commented on docs/docs/quick-start.md
> +વિશિષ્ટ કમાન્ડ માટે, `gatsby COMMAND_NAME --help` ચલાવ, ઉદાહરણ તરીકે `gatsby new --help`.
```suggestion
વિશિષ્ટ કમાન્ડ માટે, `gatsby COMMAND_NAME --help` ચલાવો, ઉદાહરણ તરીકે `gatsby new --help`.
```

2019-11-27 19:39 UTC, kishanjasani commented
@mrmakadia94 Please do not resolve the changes that you have made. The reviewer will resolve once he checked.

2019-11-28 17:31 UTC, mrmakadia94 commented
Hello @kishanjasani 
as you say that don't resolve the changes so i did changes and review that :)

2019-11-29 05:34 UTC, kishanjasani commented on docs/docs/quick-start.md
> +**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી કમાન્ડ `npx gatsby new` ચાલવો એ `gatsby ne
```suggestion
**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી કમાન્ડ `npx gatsby new` ચલાવો એ `gatsby new` ચલાવવા જેવું જ છે.
```

2019-11-29 05:34 UTC, kishanjasani commented on docs/docs/quick-start.md
> +**નોંધ**: આ વિડિઓ માં `npx` નો ઉપયોગ  થયો છે, જે npm પેકેજને પ્રથમ ઇન્સ્ટોલ કર્યા વિના ચલાવવાનું એક સાધન છે. તમારા કમ્પ્યુટર પર Gatsby-CLI સ્થાપિત કર્યા પછી કમાન્ડ `npx gatsby new` ચાલવો એ `gatsby ne
@mrmakadia94 Please see changes properly I have added two words to change here.

2019-12-02 16:55 UTC, mrmakadia94 commented
please review changes

2019-12-02 19:11 UTC, kishanjasani approved these changes

2019-12-04 20:42 UTC, sagarnasit approved these changes

2019-12-04 20:43 UTC, merged